version: '3.8'

services:
  # MongoDB for storing crawled data
  mongodb:
    image: mongo:5.0
    container_name: webcrawler-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: webcrawler
    volumes:
      - mongodb_data:/data/db
    networks:
      - webcrawler-network

  # Redis for URL frontier and coordination
  redis:
    image: redis:7-alpine
    container_name: webcrawler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webcrawler-network

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: webcrawler-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - webcrawler-network

  # Kafka for distributed messaging
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: webcrawler-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    networks:
      - webcrawler-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  webcrawler-network:
    driver: bridge
