version: '3.8'

services:
  # MongoDB - Stores crawled data and session information
  mongodb:
    image: mongo:6.0
    container_name: webcrawler-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: webcrawler
    command: mongod --bind_ip_all --logpath /var/log/mongodb/mongod.log --logappend
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
    networks:
      - webcrawler-network

  # Redis - URL frontier and distributed coordination
  redis:
    image: redis:7-alpine
    container_name: webcrawler-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --bind 0.0.0.0 --protected-mode no
    volumes:
      - redis_data:/data
    networks:
      - webcrawler-network

  # MongoDB Web UI (optional)
  mongo-ui:
    image: mongo-express:latest
    container_name: webcrawler-mongo-ui
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - webcrawler-network

  # Redis Web UI (optional)
  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: webcrawler-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8001"
    depends_on:
      - redis
    networks:
      - webcrawler-network

volumes:
  mongodb_data:
    driver: local
  mongodb_logs:
    driver: local
  redis_data:
    driver: local

networks:
  webcrawler-network:
    driver: bridge
